title: NetworkingDream
description: >
  A quiet place for lifelong learning, thoughtful tinkering,
  and enjoying the journey of computing.
url: https://livingdead1989.github.io
baseurl: "/networkingdream"   # set to "/repo-name" if not a user site

markdown: kramdown

permalink: /blog/:title/

collections:
  projects:
    output: true
    permalink: /projects/:name/

